# Generated by Django 5.0.4 on 2025-03-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinolar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='janiri',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='janiri',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
    ]
