# Generated by Django 5.0.4 on 2025-03-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinolar', '0002_rename_name_category_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
