# Generated by Django 5.0.4 on 2025-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinolar', '0007_rename_category_categorykino_remove_movie_janiri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDavlati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorydavlati', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
