# Generated by Django 5.0.4 on 2025-03-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinolar', '0008_categorydavlati'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorytili', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(upload_to='media/')),
                ('davomiyligi', models.CharField(max_length=100, null=True)),
                ('categorydavlati', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinolar.categorydavlati')),
                ('categorykinolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinolar.categorykino')),
                ('categorytili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinolar.categorytili')),
            ],
        ),
    ]
