# Generated by Django 5.0.4 on 2025-03-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinolar', '0010_categoryyili_movie_categoryyili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryyili',
            name='categoryyili',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
